export const PERMISSIONS = {
    DASHBOARD_ACCESS: "DASHBOARD_ACCESS",
    LOANS_READ: "LOANS_READ",
    LOANS_WRITE: "LOANS_WRITE",
    CUSTOMERS_READ: "CUSTOMERS_READ",
    CUSTOMERS_WRITE: "CUSTOMERS_WRITE",
    AUCTIONS_READ: "AUCTIONS_READ",
    AUCTIONS_WRITE: "AUCTIONS_WRITE",
    PAYMENTS_READ: "PAYMENTS_READ",
    PAYMENTS_WRITE: "PAYMENTS_WRITE",
    VALUATIONS_READ: "VALUATIONS_READ",
    VALUATIONS_WRITE: "VALUATIONS_WRITE",
} as const

export type Permission = keyof typeof PERMISSIONS

export const PERMISSION_LABELS: Record<string, string> = {
    [PERMISSIONS.DASHBOARD_ACCESS]: "Access Dashboard",
    [PERMISSIONS.LOANS_READ]: "View Loans",
    [PERMISSIONS.LOANS_WRITE]: "Manage Loans",
    [PERMISSIONS.CUSTOMERS_READ]: "View Customers",
    [PERMISSIONS.CUSTOMERS_WRITE]: "Manage Customers",
    [PERMISSIONS.AUCTIONS_READ]: "View Auctions",
    [PERMISSIONS.AUCTIONS_WRITE]: "Manage Auctions",
    [PERMISSIONS.PAYMENTS_READ]: "View Payments",
    [PERMISSIONS.PAYMENTS_WRITE]: "Process Payments",
    [PERMISSIONS.VALUATIONS_READ]: "View Valuations",
    [PERMISSIONS.VALUATIONS_WRITE]: "Perform Valuations",
}
